const initialState = {

  projects: [
    {
      id: 1,
      name: 'JavaScript Blog',
      code: "javascript",
      created: "bootcamp",
      responsivness:"no",
      cardFrontStyle: 'blogPage',
      cardBackStyle: 'blogCode',
      tools: 'Javascript, HTML, CSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 2,
      name: 'Pizzeria',
      code: "javascript",
      created: "bootcamp",
      responsivness:"no",
      cardFrontStyle: 'pizzeriaPage',
      cardBackStyle: 'pizzeriaCode',
      tools: 'Javascript, HTML, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 3,
      name: 'To-Do List',
      code: "react",
      created: "bootcamp",
      responsivness:"no",
      cardFrontStyle: 'ToDoPage',
      cardBackStyle: 'ToDoCode',
      tools: 'React, Redux, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 4,
      name: 'Rzeszów City',
      code: "javascript",
      created: "by-me",
      responsivness:"yes",
      cardFrontStyle: 'cityPage',
      cardBackStyle: 'cityCode',
      tools: 'Javascript, HTML, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 5,
      name: 'Drag&Drop Project',
      code: "javascript",
      created: "course",
      responsivness:"yes",
      cardFrontStyle: 'dragDropPage',
      cardBackStyle: 'dragDropCode',
      tools: 'Typescript, HTML, CSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 6,
      name: 'Receipe Book',
      code: "angular",
      created: "course",
      responsivness:"yes",
      cardFrontStyle: 'receipeBookPage',
      cardBackStyle: 'receipeBookCode',
      tools: 'Angular, NgRx, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 7,
      name: 'Fitness App',
      code: "angular",
      created: "course",
      responsivness:"yes",
      cardFrontStyle: 'fitnessAppPage',
      cardBackStyle: 'fitnessAppCode',
      tools: 'Angular, NgRx, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 8,
      name: 'Portfolio',
      code: "react",
      created: "by-me",
      responsivness: "yes",
      cardFrontStyle: 'portfolioPage',
      cardBackStyle: 'portfolioCode',
      tools: 'React, Redux, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    },
    {
      id: 9,
      name: 'Nutrition App',
      code: "angular",
      created: "by-me",
      responsivness:"yes",
      cardFrontStyle: 'nutritionAppPage',
      cardBackStyle: 'nutritionAppCode',
      tools: 'Javascript, HTML, SCSS',
      pageLink: 'https://github.com/Soszka/Javascript-blog',
      githubLink: 'https://soszka.github.io/Javascript-blog',
    }
  ]
};

export default initialState;